name: kernel

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        bash ./scripts/build-images.sh
        ls -al images
      shell: bash
