name: kernel

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        pwd
        ls -al
        bash ./scripts/build-images.sh
      shell: bash
