name: test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check kvm
      run: |
        sudo apt-get update && sudo apt-get install -yq cpu-checker
        sudo kvm-ok
      shell: bash
