name: kernel

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          dist
        key: ${{ runner.os }}-${{ hashFiles('dist/**') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: build
      run: |
        pwd
        printenv
        sudo apt-get update && sudo apt-get install -yq tree
        bash ./scripts/firecracker.sh
        bash ./scripts/buildroot.sh
        tree --du -h output/images
        docker build . -t docker.io/alexeldeib/test:dev
        # docker run --rm test
        # stat -c "%n %s" images/jammy/jammy.*
      shell: bash
